services:
  - type: web
    name: march-madness
    runtime: node
    buildCommand: cd server && npm install && cd ../client && npm install && npm run build
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
